name: Fuad Efendi
avatar: assets/favicon.png # Avatar image. Default to "images/profile.webp".
bio: 'Capital Markets, Blockchain, Web3'
company: Tokenizer Inc. # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Toronto, Ontario, Canada # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: fuad@efendi.ca
  github: FuadEfendi
  #twitter: razonyang
  #patreon: razonyang
  paypal: FuadEfendi
  rss: "" # Remove RSS
