[build]
publish = "public"

[build.environment]
NODE_VERSION = "16.17.0"
HUGO_VERSION = "0.104.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.19.1"

[context.production]
command = "npm install && hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
#     cache-control = '''
#       public,
#       max-age=900,
#       must-revalidate'''

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

